# Generated by Django 5.2.6 on 2025-11-24 17:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('banner', models.FileField(blank=True, null=True, upload_to='blog_banner/')),
                ('alt_text', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=200)),
                ('fileformat', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
                ('file', models.FileField(upload_to='uploads/job/')),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('simple_category', models.CharField(max_length=50)),
                ('medium_category', models.CharField(blank=True, max_length=50, null=True)),
                ('complex_category', models.CharField(max_length=50)),
                ('super_complex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='serviceCategory/')),
                ('ServiceCategory', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Staff/')),
                ('image_alt_text', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=250)),
                ('fb_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('twitter_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('instagram_link', models.URLField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeforAfterImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_img', models.FileField(upload_to='before_after_img/')),
                ('before_img_alt_text', models.CharField(blank=True, max_length=650, null=True)),
                ('after_img', models.FileField(upload_to='before_after_img/')),
                ('after_img_alt_text', models.CharField(blank=True, max_length=450, null=True)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envisionApp.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('service_img', models.FileField(blank=True, null=True, upload_to='service_img/')),
                ('img_alt_text', models.CharField(blank=True, max_length=450, null=True)),
                ('description', models.CharField(max_length=250)),
                ('about_em', models.CharField(max_length=50)),
                ('working_process_h2', models.CharField(max_length=250)),
                ('step_1_p', models.CharField(max_length=250)),
                ('step_2_p', models.CharField(max_length=250)),
                ('pricing_h2', models.CharField(max_length=250)),
                ('basic_plan', models.CharField(max_length=50)),
                ('bli_1', models.CharField(blank=True, max_length=100, null=True)),
                ('bli_2', models.CharField(blank=True, max_length=100, null=True)),
                ('standard_plan', models.CharField(max_length=50)),
                ('sli_1', models.CharField(blank=True, max_length=100, null=True)),
                ('sli_2', models.CharField(blank=True, max_length=100, null=True)),
                ('premium_plan', models.CharField(max_length=50)),
                ('pli_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pli_2', models.CharField(blank=True, max_length=100, null=True)),
                ('ServiceCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envisionApp.servicecategory')),
            ],
        ),
    ]
