# Generated by Django 5.2.6 on 2025-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='about_em',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='about_service',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
