# Generated by Django 5.2.6 on 2025-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0002_remove_servicedetail_about_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='service_features1',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_features2',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_features3',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_features4',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_features5',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
