# Generated by Django 5.2.6 on 2025-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0004_alter_servicedetail_service_features3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='service_features2',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
    ]
