# Generated by Django 5.2.6 on 2025-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0005_alter_servicedetail_service_features2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
