# Generated by Django 5.2.6 on 2025-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0006_message_subject_alter_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_image', models.FileField(upload_to='intro-image/')),
                ('intro_overlay_image', models.FileField(upload_to='intro-image/')),
            ],
        ),
    ]
