# Generated by Django 5.2.6 on 2025-11-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0006_message_subject_alter_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='ServiceCategory',
            new_name='servicecategory_name',
        ),
    ]
