# Generated by Django 5.2.6 on 2025-12-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0007_additionalimage'),
        ('envisionApp', '0007_rename_servicecategory_servicecategory_servicecategory_name'),
    ]

    operations = [
    ]
