# Generated by Django 5.2.6 on 2025-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envisionApp', '0008_merge_20251207_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='intro_image',
            field=models.FileField(upload_to='intro_image/'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='intro_overlay_image',
            field=models.FileField(upload_to='intro_image/'),
        ),
    ]
